# Code generated by Nitric SDK generator. DO NOT EDIT.

import grpc
from sdk.gen.storage.v2 import storage_pb2_grpc
from sdk.buckets import Bucket

class NitricClient:
    def __init__(self, address: str = "localhost:50051"):
        self._channel = grpc.aio.insecure_channel(address)
        self._storage_client = storage_pb2_grpc.StorageStub(self._channel)

        
        self.image = Bucket(self._storage_client, "image")
        

    async def close(self):
        await self._channel.close()

